name: pomo_tempus
description: 'A pomodoro timer application for Windows'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  windows_notification: ^1.3.0
  msix: ^3.16.8
  provider: ^6.1.2
  go_router: ^14.8.1
  flutter_colorpicker: ^1.1.0
  shared_preferences: ^2.5.2
  app_links: ^6.4.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.3
  freezed: ^3.0.4
  build_runner: ^2.4.15
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true

  assets:
    - assets/icon/pomo_tempus_icon.png

flutter_launcher_icons:
  image_path: 'assets/icon/pomo_tempus_icon.png'
  windows:
    generate: true
    image_path: 'assets/icon/pomo_tempus_icon.png'
    icon_size: 256 # min:48, max:256, default: 48

msix_config:
  display_name: Pomo Tempus
  publisher_display_name: Samyr Ribeiro
  logo: assets/icon/pomo_tempus_icon.png
  msix_version: 1.0.0.0
  capabilities: userNotificationListener
